"""English, synthetic scenario reference catalogue for the 2026 release.

These are *author-authored counterfactual templates*, not observations, patient
records, diagnostic labels, clinical decision rules, or a complete list of
clinical presentations.  The generator must create fresh synthetic values,
timestamps and identifiers; it must never copy source trajectories or attach a
scenario id/priority to a model input.  ``interpretation`` is deliberately
cautious and is intended only as an optional, separately-held SFT reference.

``target_overrides`` contains approximate numeric generation targets.  Scaling,
temporal smoothing, source provenance, calibration, schema selection and
quality serialization belong to the caller.  Values absent from an override
remain under the caller's baseline model.  ``weight_delta_kg`` and body-
composition deltas are relative to that synthetic person's established
baseline, rather than an assertion about a real person.
"""

from __future__ import annotations

from collections import Counter
from typing import Any, Final


CATALOGUE_NOTICE: Final[str] = (
    "AI-authored, unvalidated synthetic-scenario reference. It is not a "
    "clinical gold standard, diagnosis, triage service, or source observation."
)


def _q(status: str = "good", score: float = 0.94, coverage: float = 0.98,
       artifacts: tuple[str, ...] = ()) -> dict[str, Any]:
    """Return a generator-facing quality profile, not an observed device fact."""
    return {
        "status": status,
        "score": score,
        "coverage_ratio": coverage,
        "artifact_codes": list(artifacts),
    }


def _s(
    scenario_id: str,
    title: str,
    family: str,
    pattern: str,
    history: str,
    symptoms: dict[str, str],
    interpretation: str,
    alternative: str,
    action: str,
    uncertainty: str,
    priority: str,
    targets: dict[str, float],
    quality: dict[str, Any],
    reasoning: str,
) -> dict[str, Any]:
    return {
        "id": scenario_id,
        "title": title,
        "family": family,
        "pattern": pattern,
        "history": history,
        "symptoms": symptoms,
        "interpretation": interpretation,
        "alternative": alternative,
        "action": action,
        "uncertainty": uncertainty,
        "priority": priority,
        "target_overrides": targets,
        "quality_profile": quality,
        "reasoning": reasoning,
    }


# Keep sibling variants in the same family.  This permits counterfactual
# evaluation without making a scenario family itself a medical label.
SCENARIOS: Final[list[dict[str, Any]]] = [
    _s("baseline_rest_stable", "Stable resting baseline", "baseline_context",
       "stable_multisensor", "A 30-day synthetic history is internally stable.",
       {"breathlessness": "absent", "chest_discomfort": "absent", "dizziness": "absent"},
       "This synthetic pattern is compatible with a stable reference interval, not a health determination.",
       "Normal-looking values can still be unrepresentative when context or coverage is missing.",
       "Continue ordinary monitoring and compare only with the synthetic person's own trend.",
       "A short synthetic window cannot establish health status.", "routine",
       {"hr": 66, "spo2": 98, "sbp": 118, "dbp": 74, "temp_c": 36.7, "activity_score": 0.12}, _q(),
       "Provides a low-variance reference for all principal vital channels."),
    _s("baseline_sleep_lower_hr", "Lower heart rate during sleep context", "baseline_context",
       "sleep_context", "The synthetic history shows lower overnight than daytime heart rate.",
       {"sleep_quality": "reported_restful", "dizziness": "absent"},
       "A lower rate in a sleep-compatible context may reflect context rather than an adverse event.",
       "Wearable contact, sleep misclassification, or baseline variation can also contribute.",
       "Retain the context and recheck trend after wakefulness; seek advice if concerning symptoms occur.",
       "The catalogue does not validate sleep staging or a safe rate for any individual.", "routine",
       {"hr": 52, "spo2": 97, "activity_score": 0.03, "accelerometer_rms": 0.06}, _q("usable", 0.82, 0.92),
       "Contrasts a low rate with sleep and low movement rather than treating it as an isolated label."),
    _s("baseline_active_higher_hr", "Higher heart rate with sustained activity", "baseline_context",
       "activity_linked_elevation", "Prior synthetic active periods show a prompt rise and recovery in heart rate.",
       {"breathlessness": "expected_with_exertion", "chest_discomfort": "absent"},
       "The paired movement and rate elevation is compatible with exertional context.",
       "Stress, fever, sensor error, or an unexpectedly intense effort may look similar.",
       "Pause and recover, then recheck at rest; seek prompt assessment if symptoms persist or are severe.",
       "Activity intensity and exertional tolerance are not clinically calibrated here.", "routine",
       {"hr": 124, "activity_score": 0.83, "accelerometer_rms": 2.1, "temp_c": 37.1}, _q("good", 0.91, 0.97),
       "Makes activity an explicit explanatory feature for an otherwise elevated heart rate."),
    _s("hr_resting_tachycardia", "Persistently elevated resting heart-rate target", "heart_rate_context",
       "resting_hr_elevation", "The synthetic 7-day resting median is lower than the current repeated values.",
       {"palpitations": "present", "breathlessness": "mild", "chest_discomfort": "absent"},
       "Repeated resting elevation can have many causes, including acute illness, dehydration, stress, rhythm change, or measurement artifact.",
       "Recent activity, caffeine or other stimulants, temperature, and poor PPG contact are alternatives.",
       "Rest, repeat a good-quality reading, and arrange prompt clinical review if it persists; seek urgent help for severe symptoms.",
       "No diagnosis or rhythm classification can be made from this synthetic scalar target.", "prompt",
       {"hr": 112, "activity_score": 0.08, "accelerometer_rms": 0.12}, _q("good", 0.93, 0.98),
       "Separates resting elevation from the active-family counterpart."),
    _s("hr_transient_post_activity", "Elevated rate with reported recent activity", "heart_rate_context",
       "reported_post_activity_context", "The twice-daily history does not establish minute-scale recovery after activity.",
       {"palpitations": "brief", "breathlessness": "improving", "chest_discomfort": "absent", "recent_activity": "reported; timing and intensity not verified"},
       "An elevated rate with reported recent activity should be rechecked at rest; the supplied sampling cannot establish recovery speed.",
       "Heat, deconditioning, dehydration, unusually intense activity, or measurement timing can explain it.",
       "Stop activity, cool down and recheck after rest; arrange review if recovery remains atypical or symptoms recur.",
       "The generator does not encode exercise testing or individualized recovery thresholds.", "prompt",
       {"hr": 102, "activity_score": 0.28, "accelerometer_rms": 0.38}, _q("usable", 0.84, 0.94),
       "Distinguishes reported activity from measured recovery, which is unavailable at this cadence."),
    _s("hr_low_asymptomatic", "Lower resting heart-rate target without symptoms", "heart_rate_context",
       "low_hr_asymptomatic", "The synthetic 30-day history has comparable low resting values.",
       {"dizziness": "absent", "fainting": "absent", "breathlessness": "absent"},
       "A repeated lower rate with stable historical context may be a personal pattern, but is not proven benign.",
       "Sleep, training, device error, and unrecorded circumstances are alternatives.",
       "Recheck with good contact and discuss a new or changing pattern at a routine appointment; seek urgent help if severe symptoms appear.",
       "This is not an individualized threshold or a clinical clearance.", "routine",
       {"hr": 49, "activity_score": 0.06}, _q("good", 0.95, 0.99),
       "Pairs low value, symptoms and historical stability to avoid one-dimensional labels."),
    _s("hr_low_symptomatic", "Lower heart-rate target with concerning symptoms", "heart_rate_context",
       "low_hr_with_symptoms", "The synthetic history does not show this lower range during waking rest.",
       {"dizziness": "present", "fainting": "near_fainting", "breathlessness": "present"},
       "A low reading paired with concerning symptoms is a scenario for urgent assessment, whatever the underlying cause.",
       "Sensor error remains possible but should not be used to dismiss severe symptoms.",
       "Seek emergency evaluation now, especially for fainting, chest discomfort, severe breathlessness, or ongoing deterioration.",
       "The target cannot determine cause, severity, or whether a reading is accurate.", "emergency",
       {"hr": 42, "activity_score": 0.05}, _q("good", 0.93, 0.97),
       "Counterfactual partner to the asymptomatic low-rate pattern, with symptoms changing the safe response."),
    _s("bp_repeated_high", "Repeated elevated blood-pressure targets", "blood_pressure_trend",
       "repeated_bp_elevation", "Several synthetic home readings over days exceed the person's prior baseline.",
       {"headache": "absent", "chest_discomfort": "absent", "neurologic_symptoms": "absent"},
       "Repeated higher readings may warrant evaluation; a single measurement cannot establish a condition.",
       "Cuff position, timing, recent activity, stress, and device calibration can affect readings.",
       "Repeat using the device instructions at rest and arrange timely clinical review if the pattern continues.",
       "The catalogue does not prescribe diagnostic thresholds or treatment changes.", "same_day",
       {"sbp": 166, "dbp": 98, "hr": 78, "activity_score": 0.06}, _q("good", 0.96, 1.0),
       "Uses a multi-day pattern, because BP inference from one reading is weak."),
    _s("bp_transient_after_activity", "Temporarily higher blood-pressure target after activity", "blood_pressure_trend",
       "contextual_bp_elevation", "The synthetic prior resting BP trend is stable; this reading follows movement.",
       {"chest_discomfort": "absent", "breathlessness": "improving"},
       "A post-activity reading can be context-sensitive and should be compared with a rested repeat.",
       "Measurement timing, talking, posture, and cuff placement may contribute.",
       "Rest quietly and repeat according to device instructions; seek prompt advice if repeated elevations or symptoms occur.",
       "No isolated value in this reference is a diagnosis.", "routine",
       {"sbp": 154, "dbp": 88, "hr": 108, "activity_score": 0.58}, _q("usable", 0.79, 0.9, ("motion",)),
       "Counterfactual to repeated rested elevation: activity and a modest quality reduction are explicit."),
    _s("bp_low_postural_context", "Lower blood-pressure target after standing", "blood_pressure_trend",
       "postural_context", "Synthetic measurements are usually taken seated; the current one follows a position change.",
       {"dizziness": "brief_on_standing", "fainting": "absent"},
       "A lower reading with position-related dizziness could reflect a transient response and needs a careful repeat.",
       "Hydration, recent meals, medications not represented here, cuff position, and measurement error are alternatives.",
       "Sit or lie down if light-headed, avoid driving if unwell, repeat safely, and seek same-day advice if symptoms persist or worsen.",
       "The catalogue has no medication data and cannot establish orthostatic physiology.", "same_day",
       {"sbp": 88, "dbp": 56, "hr": 96, "activity_score": 0.12}, _q("good", 0.94, 0.98),
       "Connects BP and symptom timing without claiming a diagnosis."),
    _s("bp_low_no_symptoms", "Lower blood-pressure target without symptoms", "blood_pressure_trend",
       "low_bp_stable_context", "The synthetic history contains similarly lower rested readings.",
       {"dizziness": "absent", "fainting": "absent", "weakness": "absent"},
       "A stable lower personal pattern may be less concerning than a new symptomatic change, but still merits context-aware review.",
       "Cuff size, timing, and baseline model selection can explain apparent low values.",
       "Repeat under usual conditions and discuss a new pattern at routine review; seek urgent help for severe symptoms.",
       "This reference does not determine an individual's safe BP range.", "routine",
       {"sbp": 94, "dbp": 60, "hr": 64}, _q(),
       "Contrasts long-standing low values with symptomatic postural change."),
    _s("bp_extreme_with_red_flags", "Marked BP target with red-flag symptoms", "blood_pressure_trend",
       "bp_red_flag_combination", "The synthetic series has a sudden departure from prior readings.",
       {"chest_discomfort": "present", "neurologic_symptoms": "present", "severe_headache": "present"},
       "A marked reading combined with chest, neurologic, or severe symptoms is an emergency scenario independent of the exact cause.",
       "Incorrect measurement is possible, but red-flag symptoms require immediate attention.",
       "Seek emergency care now; do not rely on repeated home readings to delay help when red-flag symptoms are present.",
       "This template deliberately avoids a diagnostic claim and does not replace emergency triage.", "emergency",
       {"sbp": 192, "dbp": 118, "hr": 92}, _q("good", 0.97, 1.0),
       "Places urgency on symptom-plus-pattern rather than an isolated algorithmic label."),
    _s("spo2_low_rest_with_breathlessness", "Lower oxygen-saturation target at rest with breathlessness", "oxygenation_context",
       "resting_desaturation", "Synthetic prior values were higher and the low target repeats in quiet context.",
       {"breathlessness": "present_at_rest", "chest_discomfort": "absent", "cyanosis": "unknown"},
       "A repeated low saturation target with breathlessness may reflect respiratory, circulatory, or measurement issues and requires urgent assessment.",
       "Cold skin, poor perfusion, motion, nail coverings, and device limitations can yield misleading readings.",
       "Seek emergency help for severe breathing difficulty, blue/grey appearance, confusion, or worsening symptoms; otherwise obtain urgent clinical advice.",
       "Wearable SpO2 is not a diagnostic reference and this template has no validated cutoff.", "emergency",
       {"spo2": 87, "hr": 108, "respiration_rate": 25, "activity_score": 0.04}, _q("usable", 0.77, 0.88),
       "Combines rest context, repeat pattern, symptoms and plausible measurement limits."),
    _s("spo2_borderline_chronic_pattern", "Stable lower oxygen-saturation target in chronic pattern", "oxygenation_context",
       "stable_lower_spo2", "A 30-day synthetic history repeatedly occupies a similar range with no abrupt decline.",
       {"breathlessness": "baseline_only", "chest_discomfort": "absent", "confusion": "absent"},
       "A stable lower personal pattern should not be equated with normality; change from baseline and symptoms remain important.",
       "Device bias, altitude context not modelled here, and poor perfusion may contribute.",
       "Use the person's established clinical plan when one exists and arrange review for a change, worsening symptoms, or unreliable readings.",
       "This synthetic history is not a diagnosis or a substitute for individualized targets.", "routine",
       {"spo2": 92, "hr": 76, "respiration_rate": 18, "activity_score": 0.08}, _q("good", 0.9, 0.96),
       "Adds chronic-history context to counterbalance the acute-desaturation template."),
    _s("spo2_exertional_drop", "Oxygen-saturation target lower during activity", "oxygenation_context",
       "activity_linked_desaturation", "The synthetic baseline is higher at rest; this target occurs with continuous activity.",
       {"breathlessness": "more_than_usual_with_activity", "chest_discomfort": "absent"},
       "An activity-linked fall may warrant prompt assessment when it is new or paired with symptoms.",
       "Motion artifact and reduced peripheral signal quality are especially plausible during movement.",
       "Stop activity, rest and repeat with good contact; seek urgent care for severe or persistent breathlessness or concerning symptoms.",
       "The generated trace cannot measure exertional capacity or confirm true desaturation.", "prompt",
       {"spo2": 90, "hr": 128, "activity_score": 0.76, "accelerometer_rms": 1.8}, _q("usable", 0.7, 0.84, ("motion",)),
       "Makes both exertion and artifact susceptibility visible to downstream evaluation."),
    _s("rr_fast_with_fever_context", "Faster respiratory-rate target with fever context", "respiration_temperature",
       "tachypnea_fever_context", "The synthetic 7-day RR and temperature medians are lower.",
       {"feverish": "present", "cough": "present", "breathlessness": "mild"},
       "A faster respiratory pattern with feverish symptoms can occur with many acute illnesses and should be assessed in context.",
       "Recent activity, anxiety, sensor estimation error, and ambient temperature can look similar.",
       "Rest and recheck; seek same-day clinical advice if feverish symptoms or fast breathing persist, and emergency help if breathing is severe.",
       "Respiratory rate may be unavailable in the canonical contract and is a synthetic auxiliary field only.", "same_day",
       {"respiration_rate": 24, "temp_c": 38.2, "hr": 105, "spo2": 95}, _q("usable", 0.83, 0.92),
       "Models a cross-signal acute-context pattern without assigning an illness label."),
    _s("rr_fast_anxiety_context", "Faster respiratory-rate target in stress context", "respiration_temperature",
       "tachypnea_stress_context", "The synthetic history has short-lived similar episodes during recorded stress contexts.",
       {"anxiety": "present", "tingling": "present", "chest_discomfort": "absent"},
       "Stress can be one explanation for a transient faster rate, but physical causes cannot be excluded by a context tag.",
       "Activity, fever, airway symptoms, and sensor error remain alternatives.",
       "Pause, use a comfortable resting position, recheck, and obtain prompt assessment if symptoms are new, severe, or do not settle.",
       "The scenario does not diagnose anxiety or rule out medical causes.", "prompt",
       {"respiration_rate": 23, "hr": 106, "spo2": 97, "activity_score": 0.1}, _q("usable", 0.81, 0.9),
       "Supplies a non-infectious counterfactual for similar RR/HR values."),
    _s("temp_feverish_rest", "Raised body-temperature target at rest", "respiration_temperature",
       "feverish_rest_pattern", "The synthetic temperature trend rose across several hours from its personal baseline.",
       {"feverish": "present", "aches": "present", "cough": "unknown"},
       "A sustained raised temperature target with symptoms can be compatible with an acute process, among other causes.",
       "Recent exercise, warm environment, device placement, and calibration drift may affect a wearable temperature.",
       "Rest, hydrate as appropriate, repeat with a reliable method, and seek same-day advice for persistent or worsening symptoms.",
       "Wearable temperature is not interchangeable with a validated core-temperature measurement.", "same_day",
       {"temp_c": 38.4, "hr": 98, "respiration_rate": 20, "activity_score": 0.05}, _q("usable", 0.84, 0.95),
       "Uses a trend and symptoms, not a single temperature as a diagnostic label."),
    _s("temp_post_exercise_elevation", "Mild temperature elevation after activity", "respiration_temperature",
       "post_activity_temperature", "The synthetic temperature target returns toward baseline after activity stops.",
       {"feverish": "absent", "aches": "absent", "breathlessness": "improving"},
       "A modest post-activity increase can be context-related and should be interpreted after recovery.",
       "Warm surroundings, sensor site and lag can all influence the value.",
       "Cool down, rest, and repeat later; seek advice if temperature remains elevated or symptoms develop.",
       "This template does not establish fever or exclude it.", "routine",
       {"temp_c": 37.5, "hr": 104, "activity_score": 0.65, "accelerometer_rms": 1.4}, _q("good", 0.89, 0.95),
       "Counterfactual to feverish rest: time and activity explain the same-channel change."),
    _s("temp_low_contact_artifact", "Low peripheral-temperature target with contact concern", "respiration_temperature",
       "temperature_contact_artifact", "Other synthetic vital targets remain near the personal baseline.",
       {"feeling_cold": "unknown", "dizziness": "absent"},
       "An isolated low peripheral temperature target with poor contact is more consistent with a data-quality issue than a dependable physiological inference.",
       "Ambient exposure and genuine peripheral cooling are also possible.",
       "Warm and reposition the device, then repeat; seek care based on symptoms rather than this unverified value alone.",
       "Skin/peripheral temperature and core temperature are not equivalent.", "routine",
       {"temp_c": 34.7, "hr": 68, "spo2": 97, "activity_score": 0.04}, _q("poor", 0.35, 0.46, ("device_contact",)),
       "A quality-negative counterfactual prevents treating every extreme temperature target as physiological."),
    _s("weight_gradual_increase", "Gradual weight increase target", "weight_composition_trend",
       "gradual_weight_uptrend", "The synthetic 30-day weight trend rises gradually with consistent scale timing.",
       {"swelling": "absent", "breathlessness": "absent"},
       "A gradual change can reflect many factors and is most useful when viewed over time rather than as one reading.",
       "Scale placement, clothing, meals, hydration, and modelled baseline drift can contribute.",
       "Use consistent measurement conditions and discuss a sustained unexpected change at routine review.",
       "The synthetic scale fields cannot identify the cause of weight change.", "routine",
       {"weight_delta_kg": 2.1, "body_fat_pct_delta": 0.8, "activity_score": 0.23}, _q("good", 0.95, 1.0),
       "Represents a slow trend and does not assign it a cause."),
    _s("weight_rapid_increase_with_swelling", "Rapid weight increase target with swelling symptoms", "weight_composition_trend",
       "rapid_weight_change", "The synthetic 7-day weight slope is substantially steeper than its preceding 30-day trend.",
       {"swelling": "present", "breathlessness": "new_or_worse"},
       "Rapid change with swelling or worsening breathlessness needs timely assessment; possible causes cannot be inferred here.",
       "Scale inconsistency, hydration, clothing, and entry errors are alternatives but do not explain away concerning symptoms.",
       "Contact a clinician the same day; seek emergency help for severe breathlessness, chest discomfort, fainting, or rapid deterioration.",
       "No fluid-status, diagnosis, or treatment inference is validated by this reference.", "same_day",
       {"weight_delta_kg": 3.0, "hr": 94, "spo2": 94, "activity_score": 0.06}, _q("good", 0.94, 0.99),
       "Pairs rate of change and symptoms, not weight alone, with a cautious action."),
    _s("weight_gradual_loss", "Gradual weight decrease target", "weight_composition_trend",
       "gradual_weight_downtrend", "The synthetic 30-day trend declines across repeated morning measurements.",
       {"appetite_change": "present", "weakness": "mild"},
       "An unplanned sustained decline can have diverse explanations and merits review in context.",
       "Measurement routine, hydration, activity changes, and composition-estimation error can contribute.",
       "Use consistent measurements and arrange a routine clinical discussion if the trend is unexpected or continues.",
       "The scenario does not establish whether change is intentional or identify its cause.", "routine",
       {"weight_delta_kg": -2.4, "body_fat_pct_delta": -0.7, "activity_score": 0.29}, _q("good", 0.95, 1.0),
       "Uses a multi-week pattern to distinguish drift from a one-off scale fluctuation."),
    _s("weight_day_to_day_variation", "Day-to-day weight variation target", "weight_composition_trend",
       "short_term_weight_variation", "The synthetic 30-day median is stable despite alternating daily readings.",
       {"swelling": "absent", "breathlessness": "absent"},
       "Short-term variation may be routine measurement or hydration variation and should be interpreted against a longer trend.",
       "Timing, meals, clothing, scale location, and device repeatability are alternatives.",
       "Keep measurement conditions consistent and focus on the trend; seek advice if symptoms or a sustained change occur.",
       "This template is not evidence for a specific physiological mechanism.", "routine",
       {"weight_delta_kg": 0.9, "water_pct_delta": 1.3}, _q("usable", 0.8, 0.92),
       "Provides a benign-looking temporal counterfactual to rapid, symptom-linked change."),
    _s("composition_hydration_shift", "Body-composition hydration-shift target", "weight_composition_trend",
       "composition_hydration_variation", "Synthetic weight is nearly stable while impedance-derived water and fat estimates vary.",
       {"thirst": "present", "dizziness": "mild"},
       "Composition estimates can vary with hydration and measurement conditions; symptoms should be assessed independently.",
       "Foot contact, recent exercise, meals, and algorithmic estimation error are alternatives.",
       "Recheck under consistent conditions and seek prompt advice if dizziness persists, worsens, or is accompanied by severe symptoms.",
       "Bioimpedance estimates are not direct measures of hydration or body composition.", "prompt",
       {"weight_delta_kg": -0.4, "water_pct_delta": -2.3, "body_fat_pct_delta": 1.4, "hr": 96}, _q("usable", 0.72, 0.88),
       "Keeps composition signals explicitly uncertain and linked to quality/context."),
    _s("composition_implausible_jump", "Large low-quality body-composition excursion", "weight_composition_trend",
       "composition_quality_failure", "The synthetic scale's weight is stable while composition components make a large multi-reading excursion.",
       {"symptoms": "not_recorded"},
       "A large isolated composition change with stable weight is most useful as a quality-control example, not a physiological conclusion.",
       "Bare-foot contact, wet skin, scale location, and estimation algorithm variability can explain it.",
       "Repeat under consistent conditions and avoid acting on the composition estimate alone.",
       "The catalogue does not validate any consumer composition estimate.", "routine",
       {"weight_delta_kg": 0.1, "body_fat_pct_delta": 6.2, "water_pct_delta": -5.4, "muscle_mass_kg_delta": -3.1}, _q("poor", 0.3, 0.64, ("device_contact", "out_of_range")),
       "Shows low-quality composition excursions despite stable weight; mass arithmetic remains internally constrained."),
    _s("activity_sustained_walk", "Sustained moderate activity pattern", "activity_ppg_artifact",
       "sustained_activity", "Synthetic activity and heart rate rise together over a bounded period then recover.",
       {"breathlessness": "expected_with_exertion", "chest_discomfort": "absent"},
       "Coupled movement and rate change is compatible with a sustained activity context.",
       "Sensor placement, terrain and unrecorded exertion can change the relationship.",
       "Use rest-period readings for comparison; seek assessment for unusual symptoms or poor recovery.",
       "The activity score is a generated proxy, not a validated exercise prescription.", "routine",
       {"activity_score": 0.7, "accelerometer_rms": 1.35, "hr": 116, "temp_c": 37.0}, _q("good", 0.92, 0.98),
       "Provides a clean PPG-plus-acceleration context for model contrast."),
    _s("activity_sedentary_run", "Prolonged low-activity pattern", "activity_ppg_artifact",
       "low_activity_multiweek", "The synthetic 14-day activity score is below its earlier personal baseline.",
       {"fatigue": "mild", "mood_change": "unknown"},
       "A reduced activity trend is nonspecific and may be contextual, behavioural, technical, or health-related.",
       "Device non-wear, changed routine and incomplete capture are alternatives.",
       "Check wear/coverage and discuss a sustained unexpected change at routine review, especially if accompanied by symptoms.",
       "The generated activity score cannot determine functional ability or cause.", "routine",
       {"activity_score": 0.09, "accelerometer_rms": 0.08, "hr": 72}, _q("usable", 0.8, 0.77, ("insufficient_samples",)),
       "Makes long-term activity change separate from an acute vital-sign pattern."),
    _s("ppg_motion_false_hr", "PPG heart-rate target during vigorous motion artifact", "activity_ppg_artifact",
       "motion_artifact_ppg", "Synthetic PPG-derived rate diverges sharply from neighbouring rest windows during high acceleration.",
       {"palpitations": "not_recorded", "dizziness": "absent"},
       "A high motion/low-quality PPG estimate should be treated as unreliable rather than as a dependable rhythm signal.",
       "True exertional rate elevation can coexist with artifact.",
       "Stop movement, secure the device and repeat at rest; seek care for symptoms rather than relying on the artifact-prone value.",
       "No rhythm diagnosis can be made from an artifact-flagged synthetic PPG target.", "routine",
       {"hr": 154, "activity_score": 0.94, "accelerometer_rms": 3.4}, _q("poor", 0.28, 0.51, ("motion", "insufficient_samples")),
       "Tests whether systems honour quality metadata before interpreting a high rate."),
    _s("ppg_low_perfusion_spo2", "PPG/SpO2 target with low-perfusion artifact", "activity_ppg_artifact",
       "low_perfusion_artifact", "Synthetic peripheral signal coverage drops while other context features are stable.",
       {"feeling_cold": "present", "breathlessness": "absent"},
       "Low-perfusion quality flags make both PPG rate and saturation estimates uncertain.",
       "Peripheral cooling, loose contact, and a true physiological change may each contribute.",
       "Warm and reposition the sensor, then repeat; obtain care based on symptoms or persistently concerning good-quality readings.",
       "This scenario cannot distinguish sensor bias from a physiological cause.", "prompt",
       {"spo2": 89, "hr": 118, "activity_score": 0.05, "accelerometer_rms": 0.08}, _q("poor", 0.31, 0.57, ("low_perfusion", "device_contact")),
       "Adds a poor-quality counterfactual to low SpO2 without dismissing symptoms."),
    _s("ring_loose_contact", "Ring-contact low-quality episode", "activity_ppg_artifact",
       "low_contact_episode", "A contiguous low-coverage PPG episode occurs while acceleration remains low.",
       {"symptoms": "not_recorded"},
       "Poor contact can make reported vital values unreliable even when numeric output remains available.",
       "True physiological variation is possible but is not established by contact-flagged values.",
       "Check fit and skin contact, then repeat under stable conditions; do not infer a clinical event from low-quality gaps alone.",
       "Quality alignment is synthetic and not a validated device-failure classifier.", "routine",
       {"hr": 132, "spo2": 91, "activity_score": 0.04}, _q("poor", 0.22, 0.39, ("device_contact", "insufficient_samples")),
       "Represents a technical failure with low movement, distinct from motion artifact."),
    _s("ring_clock_skew", "Timestamp-order quality failure", "activity_ppg_artifact",
       "clock_skew", "Synthetic values are physiologically smooth but device-reported timestamps violate captured-time ordering. Canonical export timestamps use the simulated capture clock.",
       {"symptoms": "not_recorded"},
       "Clock skew threatens temporal interpretation even when numeric values look plausible.",
       "Transport delay, duplicate upload and source-time conversion can have similar effects.",
       "Quarantine or correct the timing metadata before trend interpretation; do not generate a clinical action from it.",
       "This is data-integrity guidance, not a patient assessment.", "routine",
       {"hr": 69, "spo2": 98, "activity_score": 0.14}, _q("poor", 0.42, 0.99, ("clock_skew",)),
       "Covers a non-physiological temporal error required for chronology-sensitive modelling."),
    _s("bp_motion_cuff_artifact", "Blood-pressure measurement with motion artifact", "technical_quality",
       "bp_motion_quality_failure", "The synthetic BP device reports a reading during movement rather than the usual seated rest interval.",
       {"symptoms": "not_recorded"},
       "A motion-affected BP target should be repeated before interpreting it as a sustained change.",
       "Cuff position, talking, posture, and recent activity may distort a reading.",
       "Rest quietly and repeat according to device instructions; seek care based on repeated reliable readings or symptoms.",
       "This template does not validate cuff-device error detection.", "routine",
       {"sbp": 174, "dbp": 103, "hr": 116, "activity_score": 0.72}, _q("poor", 0.36, 0.7, ("motion",)),
       "A BP-specific poor-quality example avoids blindly treating all high readings alike."),
    _s("scale_out_of_range", "Scale out-of-range quality failure", "technical_quality",
       "scale_out_of_range", "Synthetic scale values make a large artifact-flagged excursion across scheduled 12-hour readings.",
       {"symptoms": "not_recorded"},
       "An out-of-range quality marker makes the scale reading unsuitable for trend inference.",
       "Uneven floor, partial contact, repeated upload and calibration failure are alternatives.",
       "Reposition the scale and repeat; exclude the invalid target from trend summaries.",
       "No physiological conclusion should be drawn from this scenario.", "routine",
       {"weight_delta_kg": 12.0, "body_fat_pct_delta": -9.0}, _q("poor", 0.12, 1.0, ("out_of_range",)),
       "Represents an explicit data-exclusion case for scale pipelines."),
    _s("missing_ppg_accepted_accel", "Accelerometer retained while PPG is insufficient", "technical_quality",
       "ppg_rejected_accel_retained", "Synthetic raw ring windows contain adequate tri-axial acceleration but insufficient PPG samples.",
       {"symptoms": "not_recorded"},
       "Activity-derived fields may remain available when PPG-derived heart rate is not accepted.",
       "Non-wear, contact loss, optical obstruction, and processor criteria may each explain missing PPG.",
       "Preserve the missingness and quality state; do not impute a heart rate as if it were measured.",
       "This is a schema/provenance case, not a clinical pattern.", "routine",
       {"activity_score": 0.44, "accelerometer_rms": 0.92}, _q("poor", 0.18, 0.41, ("insufficient_samples",)),
       "Exercises the contract distinction between usable acceleration and rejected PPG."),
    _s("acute_fever_tachycardia", "Acute feverish and elevated-rate multi-signal target", "acute_multisignal",
       "acute_fever_hr_rr", "The synthetic history was stable before a several-hour joint rise in temperature, heart rate and RR.",
       {"feverish": "present", "aches": "present", "breathlessness": "mild"},
       "A coordinated acute change can have infectious and non-infectious explanations and should be assessed with symptoms and trend.",
       "Recent exertion, ambient heat, stress, and measurement artifacts remain alternatives.",
       "Recheck with good-quality measurements and seek same-day clinical advice if symptoms persist or worsen; use emergency services for severe symptoms.",
       "This template does not diagnose an infection or validate a severity score.", "same_day",
       {"temp_c": 38.5, "hr": 116, "respiration_rate": 23, "spo2": 95, "activity_score": 0.05}, _q("good", 0.9, 0.97),
       "Multi-signal temporal coordination is stronger training context than one isolated abnormal target."),
    _s("acute_dehydration_like_context", "Volume-loss-like context with trend change", "acute_multisignal",
       "volume_loss_context", "Synthetic weight declines over days while resting rate rises relative to baseline.",
       {"thirst": "present", "dizziness": "present", "vomiting_or_diarrhea": "present"},
       "This combination may be compatible with volume loss among many causes and warrants clinical assessment.",
       "Scale timing, intake changes, fever, medications not represented here, and measurement error are alternatives.",
       "Seek same-day advice, especially if unable to keep fluids down; seek emergency help for fainting, confusion, severe weakness, or worsening symptoms.",
       "The scenario neither measures volume status nor recommends a treatment regimen.", "same_day",
       {"weight_delta_kg": -2.0, "hr": 110, "sbp": 92, "dbp": 58, "temp_c": 37.7}, _q("usable", 0.84, 0.94),
       "Links trend direction, vitals and symptoms while explicitly retaining uncertainty."),
    _s("acute_chest_symptom_red_flag", "Vital change with chest-discomfort red flag", "acute_multisignal",
       "chest_symptom_red_flag", "The synthetic baseline is stable before a new symptomatic episode.",
       {"chest_discomfort": "present", "breathlessness": "present", "sweating": "present"},
       "New chest discomfort with breathlessness or sweating is an emergency scenario regardless of what the wearable targets show.",
       "Data artifacts or non-cardiac causes are possible but cannot safely resolve the symptom combination.",
       "Seek emergency care now; do not drive yourself if severely unwell and do not wait for more wearable readings.",
       "This is safety-oriented symptom guidance, not a diagnosis based on the generated values.", "emergency",
       {"hr": 122, "spo2": 93, "sbp": 158, "dbp": 94, "respiration_rate": 24}, _q("usable", 0.8, 0.92),
       "Ensures red-flag symptoms outweigh apparent device precision."),
    _s("acute_neurologic_red_flag", "Vital change with neurologic red flag", "acute_multisignal",
       "neurologic_symptom_red_flag", "Synthetic trend context is insufficient to explain a sudden symptom report.",
       {"neurologic_symptoms": "sudden_new", "confusion": "present", "severe_headache": "unknown"},
       "Sudden neurologic symptoms are an emergency scenario and cannot be assessed by wearable vital targets alone.",
       "Measurement quality is irrelevant to the need for urgent symptom evaluation.",
       "Seek emergency care now and do not delay for repeat sensor readings.",
       "No neurological diagnosis or time-of-onset inference is encoded here.", "emergency",
       {"hr": 88, "sbp": 174, "dbp": 104, "spo2": 97}, _q(),
       "Tests whether a downstream model prioritizes symptoms over ostensibly reassuring oxygenation."),
    _s("chronic_bp_history_stable", "Known higher BP-history context with stable current trend", "history_counterfactual",
       "stable_chronic_bp_context", "A synthetic sensor history contains a higher BP pattern; no prior clinical review or care plan is supplied.",
       {"headache": "absent", "chest_discomfort": "absent"},
       "A stable contextual history may affect comparison but cannot establish adequacy or replace a clinician's plan.",
       "Cuff technique and ordinary variability remain relevant.",
       "Follow an established clinical monitoring plan if one exists; otherwise arrange review to establish one, and seek advice for a sustained departure or symptoms.",
       "The history is synthetic, non-identifying, and not an EHR diagnosis.", "routine",
       {"sbp": 146, "dbp": 86, "hr": 70}, _q("good", 0.95, 1.0),
       "Demonstrates history-sensitive interpretation without encoding medication or real conditions."),
    _s("chronic_spo2_history_new_drop", "Stable lower oxygen-history context with new decline", "history_counterfactual",
       "chronic_spo2_new_decline", "A synthetic 30-day lower-saturation pattern is present, but the current target is below that recent range.",
       {"breathlessness": "more_than_baseline", "fatigue": "present"},
       "A departure from a lower personal baseline with worsening symptoms may need prompt evaluation.",
       "Low perfusion, contact and device bias can contribute and should be checked.",
       "Repeat with good contact and obtain urgent clinical advice for a sustained decline or worsening breathing; seek emergency help for severe symptoms.",
       "This does not assign a chronic diagnosis or individualized target range.", "prompt",
       {"spo2": 88, "hr": 98, "respiration_rate": 22, "activity_score": 0.07}, _q("usable", 0.76, 0.9),
       "Pairs chronic-history stability with an acute departure, avoiding an absolute-only interpretation."),
    _s("history_missing_context", "No usable historical context", "history_counterfactual",
       "history_unavailable", "No eligible synthetic prior observations pass the caller's quality and temporal rules.",
       {"symptoms": "not_recorded"},
       "Without a trustworthy trend, interpretation should remain limited to the current quality and reported context.",
       "A new device, data gap, clock error, or non-wear can explain the missing history.",
       "Establish repeated good-quality measurements under consistent conditions; seek care according to symptoms or concerning current readings.",
       "Absence of history is not evidence of absence of a prior pattern.", "routine",
       {"hr": 88, "spo2": 96, "sbp": 132, "dbp": 82, "activity_score": 0.16}, _q("usable", 0.77, 0.68, ("insufficient_samples",)),
       "Exercises uncertainty handling when historical features should be omitted or marked unavailable."),
    _s("device_cross_sensor_discordance", "Cross-sensor discordance quality example", "technical_quality",
       "cross_sensor_discordance", "Synthetic PPG heart-rate targets disagree repeatedly with contemporaneous BP-monitor pulse targets.",
       {"palpitations": "not_recorded", "dizziness": "absent"},
       "Cross-device disagreement calls for verification and provenance review before selecting one value as truth.",
       "Different timing, motion, contact, algorithms and true rapid changes are alternatives.",
       "Repeat measurements at rest with documented device context; seek care if symptoms are concerning.",
       "The catalogue cannot adjudicate device accuracy or a rhythm from disagreement alone.", "routine",
       {"hr": 128, "sbp": 122, "dbp": 76, "activity_score": 0.05}, _q("usable", 0.68, 0.86, ("device_contact",)),
       "Adds provenance-aware ambiguity instead of silently merging heterogeneous sensors."),
]


PRIORITIES: Final[frozenset[str]] = frozenset({"emergency", "same_day", "prompt", "routine"})
REQUIRED_FIELDS: Final[frozenset[str]] = frozenset({
    "id", "title", "family", "pattern", "history", "symptoms", "interpretation",
    "alternative", "action", "uncertainty", "priority", "target_overrides",
    "quality_profile", "reasoning",
})


def validate_catalogue() -> None:
    """Raise ``ValueError`` if a hand-edited template violates catalogue invariants."""
    ids = [entry["id"] for entry in SCENARIOS]
    if len(ids) != len(set(ids)):
        raise ValueError("Scenario ids must be unique")
    for entry in SCENARIOS:
        absent = REQUIRED_FIELDS.difference(entry)
        if absent:
            raise ValueError(f"{entry.get('id', '<unknown>')}: missing {sorted(absent)}")
        if entry["priority"] not in PRIORITIES:
            raise ValueError(f"{entry['id']}: unknown priority {entry['priority']!r}")
        quality = entry["quality_profile"]
        if quality["status"] not in {"good", "usable", "poor", "unknown"}:
            raise ValueError(f"{entry['id']}: invalid quality status")
        if not 0 <= quality["score"] <= 1 or not 0 <= quality["coverage_ratio"] <= 1:
            raise ValueError(f"{entry['id']}: quality score/coverage must be in [0, 1]")
        if not isinstance(entry["symptoms"], dict) or not isinstance(entry["target_overrides"], dict):
            raise ValueError(f"{entry['id']}: symptoms and target_overrides must be mappings")
        if not all(isinstance(value, (int, float)) for value in entry["target_overrides"].values()):
            raise ValueError(f"{entry['id']}: target overrides must be numeric")


SCENARIO_COUNTS: Final[dict[str, int]] = dict(Counter(entry["family"] for entry in SCENARIOS))
validate_catalogue()
